name: Continuous Integration

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libfuse-dev check make gcc libfuse3-dev

    - name: Set up Perl environment
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.32'

    - name: Install CPAN modules
      run: cpanm --installdeps .

    - name: Run unit tests
      run: make unitest

    - name: Run functional tests
      run: make fusetest
